# Generated by Django 2.2.5 on 2019-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191001_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='vote_type',
            field=models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=1),
        ),
    ]
